export BMMACNAME=$1
echo $BMMACNAME
bmmacaddr=$(echo $BMMACNAME|md5sum|sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/')
echo $bmmacaddr
ssh root@esx.gw.lo "rmdir -r -f /vmfs/volumes/datastore2/$1"
ssh root@esx.gw.lo "mkdir /vmfs/volumes/datastore2/$1"
scp template/nvram root@esx.gw.lo:/vmfs/volumes/datastore2/$1/nvram
cat << EOF > $1.vmx
config.version = "8"
virtualHW.version = "15"
vmci0.present = "TRUE"
floppy0.present = "FALSE"
numvcpus = "4"
memSize = "16384"
bios.bootRetry.delay = "10"
powerType.suspend = "soft"
tools.upgrade.policy = "manual"
sched.cpu.units = "mhz"
sched.cpu.affinity = "all"
vm.createDate = "1563578832207103"
scsi0.virtualDev = "lsisas1068"
scsi0.present = "TRUE"
sata0.present = "TRUE"
usb.present = "TRUE"
ehci.present = "TRUE"
scsi0:0.deviceType = "scsi-hardDisk"
scsi0:0.fileName = "${1}.vmdk"
sched.scsi0:0.shares = "normal"
sched.scsi0:0.throughputCap = "off"
scsi0:0.present = "TRUE"
ethernet0.virtualDev = "E1000e"
ethernet0.networkName = "VM Network"
ethernet0.addressType = "static"
ethernet0.address = "$bmmacaddr"
ethernet0.wakeOnPcktRcv = "FALSE"
ethernet0.uptCompatibility = "TRUE"
ethernet0.present = "TRUE"
sata0:0.startConnected = "TRUE"
sata0:0.deviceType = "cdrom-image"
sata0:0.fileName = "/vmfs/volumes/5f50f993-22a13851-1eb3-a0369f607260/iso/discovery_image_thi.iso"
sata0:0.present = "TRUE"
displayName = "${1}"
guestOS = "coreos-64"
toolScripts.afterPowerOn = "TRUE"
toolScripts.afterResume = "TRUE"
toolScripts.beforeSuspend = "TRUE"
toolScripts.beforePowerOff = "TRUE"
tools.syncTime = "FALSE"
sched.cpu.min = "0"
sched.cpu.shares = "normal"
sched.mem.min = "0"
sched.mem.minSize = "0"
sched.mem.shares = "normal"
bios.bootRetry.enabled = "TRUE"
tools.guest.desktop.autolock = "FALSE"
pciBridge0.present = "TRUE"
svga.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
hpet0.present = "TRUE"
RemoteDisplay.maxConnections = "-1"
sched.cpu.latencySensitivity = "normal"
svga.autodetect = "TRUE"
sata0:0.autodetect = "TRUE"
numa.autosize.cookie = "40012"
numa.autosize.vcpu.maxPerVirtualNode = "4"
pciBridge0.pciSlotNumber = "17"
pciBridge4.pciSlotNumber = "21"
pciBridge5.pciSlotNumber = "22"
pciBridge6.pciSlotNumber = "23"
pciBridge7.pciSlotNumber = "24"
scsi0.pciSlotNumber = "160"
usb.pciSlotNumber = "32"
ethernet0.pciSlotNumber = "192"
ehci.pciSlotNumber = "33"
vmci0.pciSlotNumber = "34"
sata0.pciSlotNumber = "35"
scsi0.sasWWID = "50 05 05 60 94 52 75 80"
monitor.phys_bits_used = "43"
vmotion.checkpointFBSize = "4194304"
vmotion.checkpointSVGAPrimarySize = "16777216"
softPowerOff = "FALSE"
usb:1.speed = "2"
usb:1.present = "TRUE"
usb:1.deviceType = "hub"
usb:1.port = "1"
usb:1.parent = "-1"
svga.guestBackedPrimaryAware = "TRUE"
toolsInstallManager.updateCounter = "1"
scsi0:0.redo = ""
ethernet1.pciSlotNumber = "224"
svga.vramSize = "16777216"
ethernet1.generatedAddressOffset = "10"
usb:0.present = "TRUE"
usb:0.deviceType = "hid"
usb:0.port = "0"
usb:0.parent = "-1"
EOF
scp $1.vmx root@esx.gw.lo:/vmfs/volumes/datastore2/$1/$1.vmx
rm $1.vmx
ssh root@esx.gw.lo "cd /vmfs/volumes/datastore2/$1;rm $1.vmdk;rm $1.vmsd;rm $1-flat.vmdk;vmkfstools --createvirtualdisk 160G --diskformat thin $1.vmdk"

ssh root@esx.gw.lo "vim-cmd solo/registervm /vmfs/volumes/datastore2/$1/$1.vmx"

